name: Infra and application deployment

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main, staging, production]

env:
  IMAGE_REPOSITORY: goal-share
  TERRAFORM_WORKING_DIR: ./terraform/infra

jobs:
  terraform-check:
    name: Validate the terraform configuration files
    runs-on: ubuntu-latest
    # this is required for authenticating to AWS via the OIDC Provider we set up
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14.3

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v3
        with:
          tflint_version: v0.52.0

      - name: Init TFLint
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: tflint --init

      - name: Run TFLint
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: tflint -f compact

      - run: terraform fmt -check
        continue-on-error: true
        working-directory: ${{ env.TERRAFORM_WORKING_DIR }}

      - name: Terraform initialization
        run: terraform init
        working-directory: ${{ env.TERRAFORM_WORKING_DIR }}

      - name: Terraform validate
        run: terraform validate
        working-directory: ${{ env.TERRAFORM_WORKING_DIR }}

  build-push:
    name: Build and Push docker image to ECR repository
    runs-on: ubuntu-latest
    # this is required for authenticating to AWS via the OIDC Provider we set up
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::287773672913:role/goal-share-go-app-ci-cd
          role-session-name: GithubActionsSession

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ env.IMAGE_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
  test:
    needs:
      - build-push
    name: Test the image and run migrations locally
    runs-on: ubuntu-latest
    # this is required for authenticating to AWS via the OIDC Provider we set up
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::287773672913:role/goal-share-go-app-ci-cd
          role-session-name: GithubActionsSession

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Pull the image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ env.IMAGE_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker image pull $REGISTRY/$REPOSITORY:$IMAGE_TAG
      - name: Run the postgres container
        run: |
          docker run -d --name postgres --env POSTGRES_PASSWORD=password --network "host" -p 5432:5432 -v postgres:/var/lib/postgresql/data postgres:alpine

      - name: Check connectivit between app and database and run migration
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: goal-share
          IMAGE_TAG: ${{ github.sha }}
          GOOSE_DBSTRING: postgresql://postgres:password@localhost:5432/postgres?sslmode=disable
          GOOSE_DRIVER: postgres
        run: |
          DOCKERIZE_URL=tcp://localhost:5432

          docker container run --entrypoint "dockerize" --network "host" --rm $REGISTRY/$REPOSITORY:$IMAGE_TAG -timeout 30s -wait $DOCKERIZE_URL

          docker container run --entrypoint "goose" --env "GOOSE_DBSTRING" --env "GOOSE_DRIVER" --network "host" --rm $REGISTRY/$REPOSITORY:$IMAGE_TAG -dir migrations status

          docker container run --entrypoint "goose" --env "GOOSE_DBSTRING" --env "GOOSE_DRIVER" --network "host" --rm $REGISTRY/$REPOSITORY:$IMAGE_TAG -dir migrations validate

          docker container run --entrypoint "goose" --env "GOOSE_DBSTRING" --env "GOOSE_DRIVER" --network "host" --rm $REGISTRY/$REPOSITORY:$IMAGE_TAG -dir migrations up
